AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('App.urls',namespace='axf')),
]

App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r"^home/",views.home,name='home'),
    url(r"^cart/", views.cart, name='cart'),
    url(r"^mine/", views.mine, name='mine'),
    url(r"^market/", views.market, name='market'),
    url(r"^marketcategory/(\d+)/(\d+)/(\d+)/", views.marketCategory, name="marketcategory"),
    url(r"^login/",views.login,name='login'),
    url(r'^dologin/',views.dologin,name='dologin'),
    url(r'^quit/',views.quit,name='quit'),
    url(r"^register/",views.register,name='register'),
    url(r"^doregister/",views.doregister,name='doregister'),
    url(r'^checkusername/',views.checkusername,name='checkuserid'),
    url(r'^success/',views.success,name='success'),
    url(r'^error/',views.error,name='error'),
    url(r'^cart/',views.Cart,name='cart'),
    url(r'^addchangecart/',views.addchangecart,name='addchangecart'),
    url(r'^subchangecart/',views.subchangecart,name='subchangecart'),
]

templates/App/Base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
        <link rel="stylesheet" href="{% static 'base/css/bootstrap-theme.css' %}">
        <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
        <link rel="stylesheet" href="{% static 'base/css/base.css'%}">
        <script type="text/javascript" src={% static 'base/js/jquery.js' %}></script>
        <script type="text/javascript" src={% static 'base/js/swiper.js' %}></script>
        <script type="text/javascript" src={% static 'base/js/bootstrap.js' %}></script>
        <script type="text/javascript" src={% static 'base/js/base.js' %}></script>

    <title>{{ pageTitle }}</title>
    {% block personResource %}

    {% endblock %}
</head>
<body>

<header>   </header>

<div>
    {% block content %}
    {% endblock %}
</div>

<footer>
    <a href="{% url 'axf:home' %}" class="home">
        <dl>
            <dt><span></span></dt>
            <dd>主页</dd>
        </dl>
    </a>
        <a href="{% url 'axf:marketcategory' 104749  0  0%}" class="market">
        <dl>
            <dt><span></span></dt>
            <dd>闪送</dd>
        </dl>
    </a>
    <a href="{% url 'axf:cart' %}" class="cart">
        <dl>
            <dt><span></span></dt>
            <dd>购物车</dd>
            <div id="redallnum">{{ redallnum }}</div>
        </dl>
    </a>
        <a href="{% url 'axf:mine'  %}" class="mine">
        <dl>
            <dt><span></span></dt>
            <dd>我的</dd>
        </dl>
    </a>

</footer>

</body>
</html>

templates/App/Cart.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">

    <script type="text/javascript" src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

{% block content %}
   <div id="cart">
    <h3><b>购物车</b></h3>

    <section class="full">
		<section>
			<ul>
				<li>
                    <div class="clear">
                        <p class="infoJustify">收货人:</p><p>吴彦祖</p>
                    </div>
                </li>
				<li>
                    <div class="clear">
                        <p class="infoJustify">电  &nbsp; 话:</p><p>110120119<a class="change">修改></a></p>
                    </div>
                </li>
				<li>
                    <div class="clear"><p class="infoJustify">地 &nbsp; 址:</p><p>正在为您定位...</p>
                    </div>
                </li>
			</ul>


			<section class="bill">
				<p>闪送超市</p>
				<p>¥0起送,22:00前满¥30免运费</p>
				<a>凑单专区</a>
			</section>


			<section class="delivery">
				<span>收货时间</span> <span>一小时送达</span> <a>可预订></a>
			</section>
			<section class="delivery">
				<span>收货备注</span> <input type="text" placeholder="可输入100字以内特殊要求内容"/>
			</section>


            <menu>
				<ul>

                    {% for item in cartslist%}
                    <li id="{{item.productid}}li" class="menuList">
                        <div class="confirm">
                            <span class="ischose" goodsid="{{item.productid}}">
                                <span id="{{item.productid}}a" >
                                {% ifequal True item.isChose %}
                                √
                                {% endifequal %}
                                </span>
                            </span>
                        </div>
                        <a href="#">
                            <img src="{{item.productimg}}"/>
                            <p>{{item.productname}}</p>
                            <span id="{{item.productid}}price" class="{{productprice}}">{{item.productprice}}</span>
                        </a>
                        <section>
                            <button class="redgoods"  ga="{{item.productid}}">-</button>
                            <span id="{{item.productid}}" class="goodsnum">{{item.productnum}}</span>

                            <button class="addgoods"  ga="{{item.productid}}">+</button>
                        </section>
                    </li>
                    {% endfor %}

					<li class="payTheBill">
						<div class="confirm"><span><span>
                            {% if trueFlag %}
                            √
                            {% endif %}
                        </span></span></div>

						<p><span>全选</span><span>共计:</span><span id = 'allnum'>{{ allnum }}</span><span>总价:</span><span id="allprice">{{ allprice }}</span></p>
						<a id="ok">选好了</a>
					</li>
				</ul>
			</menu>
		</section>
	</section>
</div>

{% endblock %}

templates/App/Error.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}
    <style>
        .success{

            height: 100%;
            width: 100%;
            padding-top: 3rem;
            line-height: 10rem;
            text-align: center;

        }
    </style>
    <script>
{#    1秒后自动跳转到登录页面#}
    var page ="{% url 'axf:login' %}"
    window.setTimeout('window.location=page',1000);

    </script>
{% endblock %}

{% block content %}
<div class="success">
    用户名/密码错误！将为你跳转......
</div>
{% endblock %}>

templates/App/Home.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
    <script type="text/javascript" src="{% static 'home/js/home.js' %}"></script>


{% endblock %}

{% block content %}
    <div id="home">

        {#        轮播#}
        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">

                {% for wheel in wheelList %}
                    <div class="swiper-slide"><img src="{{ wheel.img }}"></div>
                {% endfor %}

            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
        </div>


        {#        导航#}
        <div class="nav">

            {% for i in navList %}
                <a href="">
                    <div class="navdiv">
                        <div class=""><span><img src='{{ i.img }}'></span></div>
                        <h6>{{ i.name }}</h6>
                    </div>
                </a>
            {% endfor %}

        </div>
        {#        小轮播#}
        <div id="swiperMenu  clearFloat">
            <div class="swiper-container" id="swiperMustBuy">

                <div class="swiper-wrapper">

                    {% for mustbuy in mustBuyList %}

                        <div class="swiper-slide"><img src="{{ mustbuy.img }}"></div>

                    {% endfor %}

                </div>
            </div>

        </div>

        {#    商店十一个图#}
        <div class="shop ">
            {% for i in shop1 %}
                <a href="">
                    <div class="shop1"><img src={{ i.img }}></div>
                </a>
            {% endfor %}


            {% for i in shop2 %}
                <a href="">
                    <div class="shop2 "><img src={{ i.img }} alt=""></div>
                </a>
            {% endfor %}

            {% for i in shop3 %}
                <a href="">
                    <div class="shop3"><img src={{ i.img }} alt=""></div>
                </a>

            {% endfor %}

            {% for i in shop3 %}
                <a href="">
                    <div class="shopp"><p>{{ i.name }}</p></div>
                </a>

            {% endfor %}

            {% for i in shop4 %}
                <a href="">
                    <div class="shop4"><img src={{ i.img }} alt=""></div>
                </a>

            {% endfor %}
        </div>

        {#    下面重复的#}
        <div class="mainshow_list clearfloat">

            {% for mainshow in mainshowList %}
                <div class="hp clearfloat">
                    <h3>{{ mainshow.name }}</h3>
                    <a href="">更多>></a>
                </div>
                <div class="img1">
                    <a href="#"><img src="{{ mainshow.img }}"></a>
                </div>
                <div class="clearfloat">
                    <ul>
                        <li><a href="">
                            <img src="{{ mainshow.img1 }}">
                            <p class="longname">{{ mainshow.longname1 }}</p>
                            <p class="longprice">{{ mainshow.price1 }}</p>
                        </a>
                        </li>
                        <li><a href="">
                            <img src="{{ mainshow.img2 }}">
                            <p class="longname">{{ mainshow.longname2 }}</p>
                            <p class="longprice">{{ mainshow.price2 }}</p>
                        </a>
                        </li>
                        <li><a href="">
                            <img src="{{ mainshow.img3 }}">
                            <p class="longname">{{ mainshow.longname3 }}</p>
                            <p class="longprice">{{ mainshow.price3 }}</p>
                        </a>
                        </li>

                    </ul>
                </div>
{#                <div class="ccc"></div>#}
            {% endfor %}

            <div class="bbb"></div>
        </div>

    </div>
{% endblock %}

templates/App/Login.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}

    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">

{% endblock %}

{% block content %}
    <div id="login">
    <div id="loginTop"><p>登录</p></div>
    <a href="{% url 'axf:mine' %}"><p class="gogo">&lt;返回</p></a>
    <div id="box">
        <form action="{% url 'axf:dologin' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                用户名：<input class="theText"  type="text" name="username" placeholder=" 请输入您的用户名">
                <br />
{#                {% if error.username.0 %}#}
{#                <span>{{error.username.0}}</span>#}
{#                {% endif %}#}
            </div>
            <div class="input-group">
                 密 码： &nbsp;<input class="theText" type="password" name="userpassword" placeholder=" 请输入您的密码">
                <br />
{#                {% if error.passwd.0 %}#}
{#                <span>{{error.passwd.0}}</span>#}
{#                {% endif %}#}
            </div>
            <div class="submit">
                <input type="submit" value="登录"/>
            </div>
        </form>
        <div class="goRegister"><a href="{% url 'axf:register' %}">没有账号,去注册。</a></div>

    </div>
</div>

{% endblock %}

templates/App/Market.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
    <script type="text/javascript" src="{% static 'market/js/market.js' %}"></script>
    <script type="text/javascript" src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="Market">
        <div class="leftBox">
        <ul>
            {% for foodtype in foodtypes %}
                {% ifequal foodtype.typeid foodid %}
                <li class="">
                    <div class="yellowdiv"></div>
                    <a href="{% url 'axf:marketcategory' foodtype.typeid  0  0%}"><div class="leftSmileBox">{{foodtype.typename}}</div></a>
                </li>
                {% else %}
                <li class="">
                    <div class="yellowdiv"></div>
                    <a href="{% url 'axf:marketcategory' foodtype.typeid  0  0%}"><div class="">{{foodtype.typename}}</div></a>
                </li>
                {% endifequal %}
            {% endfor %}

        </ul>
        </div>

        <div class="topNav">

                <div class="leftNav">全部分类<span class="glyphicon glyphicon-chevron-down"></span></div>

                <div class="rightNav">综合排序<span class="glyphicon glyphicon-chevron-down"></span></div>

        </div>


        <div class="leftChildType">
            {% for item in items %}

            <a href="{% url 'axf:marketcategory' foodtypeid  item.childTypeId  orderRule %}"><div class="childType"><p>{{ item.childName }}</p></div></a>

            {% endfor %}
        </div>

        <div class="rightOrder">
            <a href="{% url 'axf:marketcategory' foodtypeid childcid  0  %}"><div class="orderrule"><p>综合排序</p></div></a>
            <a href="{% url 'axf:marketcategory' foodtypeid childcid  1  %}"><div class="orderrule"><p>价格升序</p></div></a>
            <a href="{% url 'axf:marketcategory' foodtypeid childcid  2  %}"><div class="orderrule"><p>价格降序</p></div></a>
            <a href="{% url 'axf:marketcategory' foodtypeid childcid  3  %}"><div class="orderrule"><p>库存容量</p></div></a>


        </div>

        <div class="goodsListBox">
            <ul>
            
            {% for goods in goodsList %}
                <li>
                    <a href="">
                        <div class="goodsimg">
                            <img src="{{ goods.productimg }}" alt="">
                        </div>
                        </a>
                        <div class="goodInfo">
                            <p>{{ goods.productname}}</p>
                            <p>精选</p>
                            <p>￥{{ goods.marketprice }}</p>
                            <div ga="{{ goods.productid }}" class="addgoods">+</div>
                            <span id="{{goods.productid}}" class="goodsnum">{{ i.num }}</span>

{#                            <div class="goodsnum">0</div>#}
                            <div id='{{ goods.productid }}redgoods' ga="{{ goods.productid }}" class="redgoods "><strong>-</strong></div>
                            <p>{{ goods.specifics }}</p>

                        </div>

                </li>
            {% endfor %}

            </ul>
        </div>
    </div>
{% endblock %}

templates/App/Mine.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}

    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">

{% endblock %}

{% block content %}
<div id="mine">
    <section class="fixed">
		<span class=""> <img src="{{ img }}" alt=""></span>
{#		<span class=""> <img src={% static 'uploadfile/111.png' %} alt=""></span>#}
{#		<span class=""> <img src={% static '{{ img }}'%} alt="#"></span>#}

{#        <img src="{{ img }}" alt="">#}
{#		<span class="glyphicon glyphicon-user"></span>#}
		<p><a href="{% url 'axf:login' %}">您好，{{username}}</a></p>
		<p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
		<a id="regis" href="{% url 'axf:register' %}">注册</a>
		<p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
	</section>

    <section class="mine">
		<p>
			<span>我的订单</span><a>查看全部订单&gt;</a>
		</p>
		<nav id="nav">
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-usd"></span></dt>
							<dd>待付款</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-envelope"></span></dt>
							<dd>待收货</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-pencil"></span></dt>
							<dd>待评价</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-retweet"></span></dt>
							<dd>退款/售后</dd>
						</dl>
					</a>
				</li>
			</ul>
		</nav>


		<menu>
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
							<dd>积分商城</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-credit-card"></span></dt>
							<dd>优惠券</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-import"></span></dt>
							<dd>收货地址</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
							<dd>客服/反馈</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-asterisk"></span></dt>
							<dd>关于我们</dd>
						</dl>
					</a>
				</li>
			</ul>
		</menu>
        <div class="quit">
		<p><a href="{% url 'axf:quit' %}">退出当前账号</a></p>
	    </div>
    </section>
</div>

{% endblock %}

templates/App/Register.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}

    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{#    <script type="text/javascript" src="{% static 'mine/js/register.js' %}"></script>#}
        <script type="text/javascript" src="{% static 'mine/js/Register.js' %}"></script>

{% endblock %}

{% block content %}
    <div id="register">
    <div id="registerTop">注册</div>
    <div id="header">
        <a href="{% url 'axf:mine' %}"><p>&lt;返回</p></a>
    </div>
    <form class="form-horizontal" action="{% url 'axf:doregister' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}

        <div class="input-group">
            <span class="input-group-addon">账号</span>
            <input id="name" type="text" class="form-control" placeholder="账号长度为6到12个字符" aria-describedby="basic-addon1" name="userName">
        </div>

        <span id="nameerr" class="error">账号格式输入错误</span>
        <span id="checkerr" class="error">账号已被占用，请重新输入</span>

        <br/>

        <div class="input-group">
            <span class="input-group-addon">密码</span>
            <input id="pass" type="password" class="form-control" placeholder="密码长度为6~16个字符" aria-describedby="basic-addon1" name="userPass">
        </div>

        <span id="passerr" class="error">密码格式输入错误</span>

        <br />

        <div class="input-group">
            <span class="input-group-addon">验证</span>
            <input id="passwd" type="password" class="form-control" placeholder="密码长度为6~16个字符" aria-describedby="basic-addon1" name="userPasswd">
        </div>

        <span id="passwderr" class="error">两次密码输入不同</span>

        <br/>

{#        <div class="input-group">#}
{#            <span class="input-group-addon">昵称</span>#}
{#            <input required="required" type="text" class="form-control" aria-describedby="basic-addon1" name="userName">#}
{#        </div>#}
{#        <br/>#}
        <div class="input-group">
            <span class="input-group-addon">电话</span>
            <input required="required" type="text" class="form-control" aria-describedby="basic-addon1" name="userPhone">
        </div>


        <br/>

        <div class="input-group">
            <span class="input-group-addon">地址</span>
            <input required="required" type="text" class="form-control" aria-describedby="basic-addon1" name="userAdderss">
        </div>

        <br/>

        <div class="input-group">
            <span class="input-group-addon">头像</span>
            <input required="required" type="file" class="form-control" aria-describedby="basic-addon1" name="userImg">
        </div>

        <br/>

        <div class="registerSubmit">
{#            <span class="input-group-addon">注册</span>#}
            <input  type="submit" class="form-control" aria-describedby="basic-addon1" value="注册">
        </div>
    </form>
</div>

{% endblock %}

templates/App/Success.html
{% extends 'App/Base.html' %}
{% load static %}
{% block personResource %}
    <style>
        .success{

            height: 100%;
            width: 100%;
            padding-top: 3rem;
            line-height: 10rem;
            text-align: center;

        }
    </style>
    <script>
{#    2秒后自动跳转到登录页面#}
    var page ="{% url 'axf:login' %}"
    window.setTimeout('window.location=page',2000);

    </script>
{% endblock %}

{% block content %}
<div class="success">
    操作成功！将为你跳转......
</div>
{% endblock %}